set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" Clojure
Plugin 'guns/vim-sexp'
Plugin 'tpope/vim-sexp-mappings-for-regular-people'
Plugin 'tpope/vim-fireplace'
Plugin 'guns/vim-clojure-static'
Plugin 'tpope/vim-salve'

" Haskell
Plugin 'itchyny/vim-haskell-indent' 
Plugin 'adinapoli/cumino' 
Plugin 'bitc/vim-hdevtools' 
Plugin 'eagletmt/ghcmod-vim' 
Plugin 'neovimhaskell/haskell-vim'

" Html
Plugin 'mattn/emmet-vim'

" Javascript
Plugin 'jelera/vim-javascript-syntax'
Plugin 'moll/vim-node'

" Ide stuff
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-sensible'
Plugin 'tpope/vim-surround'
Plugin 'Shougo/vimproc.vim'
Plugin 'Shougo/unite.vim'
Plugin 'Shougo/neomru.vim'
Plugin 'roman/golden-ratio'
Plugin 'sickill/vim-pasta'
Plugin 'kien/rainbow_parentheses.vim'
Plugin 'rking/ag.vim'
Plugin 'godlygeek/tabular'
Plugin 'scrooloose/syntastic'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-repeat'
Plugin 'flazz/vim-colorschemes'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'tpope/vim-sleuth'
 
" Purescript
Plugin 'raichoo/purescript-vim'
Plugin 'frigoeu/psc-ide-vim'

" Ruby 
Plugin 'tpope/vim-bundler'

" SQL
Plugin 'vim-scripts/dbext.vim'
""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Add all plugins before this
""""""""""""""""""""""""""""""""""""""""""""""""""""""""

call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
filetype plugin on

syntax on

" Tab settings
" set expandtab
" set tabstop=4
" set shiftwidth=4

" Smart searching
set ignorecase
set smartcase
set incsearch
set hlsearch

" Show line numbers
set number

" Other settings
set omnifunc=syntaxcomplete#Complete " Omni completion
set confirm
set cmdheight=1
set splitright
set splitbelow
set autowriteall
set relativenumber

let mapleader=","
let maplocalleader="\\"

" Unite
let g:unite_source_grep_default_opts = '-iRhn'
    \ . " --exclude-dir='.stack-work'"
    \ . " --exclude-dir='.git'"
    \ . " --exclude='.gitignore'"
    \ . " --exclude-dir='node_modules'"
    \ . " --exclude-dir='node_modules'"
" let g:unite_source_rec_async_command = ['ag', '--nocolor', '--nogroup', '--hidden', '-g', '""']
call unite#filters#matcher_default#use(['matcher_fuzzy'])
call unite#custom#profile('fuzzyfiles', 'context.ignorecase', 1)
call unite#custom#profile('fuzzyfiles', 'context.smartcase', 1)
call unite#custom#profile('files', 'context.ignorecase', 1)
call unite#custom#profile('files', 'context.smartcase', 1)
call unite#custom#source('file_rec,file_rec/async', 'ignore_pattern',
            \ '\.stack-work'
            \ . '\|node'
            \ . '\|jar'
            \ . '\|bower_components'
            \ . '\|output'
            \ . '\|compiled'
            \ . '\|.gitignore'
            \ . '\|dist'
            \ . '\|.DS_Store'
            \ . '\|coverage'
            \ . '\|.cabal-sandbox')

nnoremap <silent><leader>f :<C-u>Unite 
            \ -auto-preview 
            \ -buffer-name=files 
            \ -profile-name=fuzzyfiles
            \ -start-insert file_rec/async:!<cr>
nnoremap <leader><leader> :Unite -start-insert
            \ -profile-name=files
            \ buffer 
            \ file_rec
            \ file_mru<CR>

" General bindings
nnoremap <silent><space> :nohlsearch<cr>
nmap <silent><leader>ve :vsp $MYVIMRC<cr>
nmap <silent><leader>vs :so $MYVIMRC<cr>
map <F1> <Esc>
imap <F1> <Esc>
nnoremap <C-w>v :vnew<cr>

" Syntastic Settings
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0
let g:syntastic_javascript_checkers = ['eslint']
let g:syntastic_ruby_checkers = ['rubocop']

" Haskell Syntax settings
let g:haskell_enable_quantification = 1
let g:haskell_enable_recursivedo = 1
let g:haskell_enable_arrowsyntax = 1
let g:haskell_enable_pattern_synonyms = 1
let g:haskell_enable_typeroles = 1
let g:haskell_enable_static_pointers = 1
let g:haskell_indent_if = 3
let g:haskell_indent_case = 2
let g:haskell_indent_let = 4
let g:haskell_indent_where = 6
let g:haskell_indent_do = 3
let g:haskell_indent_in = 1
let g:cabal_indent_section = 2

" Cumino Settings
let g:cumino_default_terminal = "urxvt"

" ruby settings
let g:ruby_path='/Users/govind/.rbenv/versions/2.2.3/bin/ruby'
let g:syntastic_ruby_rubocop_exec = '/Users/govind/.rbenv/versions/2.2.3/bin/rubocop'

" Save on buffer change
augroup AutoSave
    autocmd!
    autocmd BufLeave,FocusLost * silent! w
augroup end

" Haskell Augroup
augroup Haskell
    autocmd!
    autocmd bufwritepost *.hs %!stylish-haskell
    autocmd bufenter *.tpl :set syntax=html
augroup end

" Javascript Augroup
augroup Javascript
    autocmd!
    autocmd bufenter *.rt set syntax=html
    autocmd bufenter *.eslintrc set syntax=json
augroup end

" RainbowParens Augroup
augroup RainbowParens
    autocmd!
    autocmd vimenter * RainbowParenthesesToggle
    autocmd syntax * RainbowParenthesesLoadRound
    autocmd syntax * RainbowParenthesesLoadSquare
    autocmd syntax * RainbowParenthesesLoadBraces
augroup end

" Ghcmod settings
map <silent> tu :call GHC_BrowseAll()<CR>
map <silent> tw :call GHC_ShowType(1)<CR>

colorscheme solarized
