# Use 256 term for pretty colors
set -g default-terminal "screen-256color"

# increase history
set -g history-limit 10000

# use vi bindings
setw -g mode-keys vi

# decrease command delay (For improved vim responsiveness)
set -sg escape-time 1

# Start window index at 1
set -g base-index 1

# Start pane index at 1
set -g pane-base-index 1

# Highlight window when there is activity
setw -g monitor-activity on
setw -g visual-activity on

# tmux prefix 
unbind C-b
set -g prefix C-a

# window splitting
unbind %
bind / split-window -h
unbind '"'
bind \ split-window -v

# Quickly switch panes
unbind ^a
bind ^a select-pane -t :.+

# Reload the config
unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Colours
set -g status-bg colour235
set -g status-fg white
set-window-option -g window-status-current-fg black
set-window-option -g window-status-current-bg green

